# Generated by Django 3.2.12 on 2022-08-27 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du livre')),
                ('nb_pages', models.IntegerField(max_length=5, verbose_name='Nombre de pages')),
                ('code_isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('summary', models.TextField(verbose_name='Résumé du livre')),
                ('publication_date', models.DateTimeField(verbose_name='Date de publication')),
                ('cover', models.URLField(verbose_name='Image de couverture')),
                ('path', models.TextField(verbose_name='Lien du fichier')),
            ],
            options={
                'verbose_name': 'Livres',
            },
        ),
    ]
